
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///booking_ticket?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: false
  #type-enums-package: cn.tedu.domain
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080